apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu
  labels:
    app: attu
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
        - name: attu
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MILVUS_URL
              value: "{{ .Values.env.MILVUS_URL }}"
          ports:
            - containerPort: 3000
